%RUNMDDPLOT Example driver for the frozen MATLAB workflow.
%   Update CASEFOLDER to point at a Delft3D-FM result directory, then run
%   this file from MATLAB.

caseFolder = '/path/to/delft3d-case';

result = mddPlot(caseFolder, ...
	'exportVideo', true, ...
	'exportSTL', false, ...
	'exportImages', false, ...
	'nameVideo', 'Simulation_Summary.avi', ...
	'nameImages', 'pngs/step_%d.png', ...
	'nameSTL', 'Final_Bed_Surface.stl', ...
	'gridRes', 10, ...
	'timeRes', 50, ...
	'visible', true);

disp(result.summary)